# Generated by Django 5.0 on 2024-01-01 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0004_categort_post_category'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Categort',
            new_name='Category',
        ),
    ]
